### ISSUE TITLE
The extension doesn't fold nested blocks

### ISSUE THREAD

**Issue by hukop** [reapler/vscode-cfold#1]
Hi,

first of all thanks for providing this extension. The current folding in VSCode is unbearable.

However I found this extension only folds the top level of the code. 
I attached two screenshots, one with the extension turned on, one with the extension turned off.
You can see without the extension there is an incorrect fold at the `#endif` And when folding the entire function it stops at the `#ifdef`
![WithoutCFold](https://user-images.githubusercontent.com/58051546/74288487-5bd10900-4ce1-11ea-934c-16b6fc49b988.jpg)

But with the extension turned on you can't fold the inner for loop anymore. And if the `#ifdef`/`#endif` block is not on the first line you can fold that block either.
![WithCFold](https://user-images.githubusercontent.com/58051546/74288478-5378ce00-4ce1-11ea-9ab6-2de1bc7b0220.jpg)

**Comment by jpramosi** [comment]
Hello, thanks for the submitted issue.

To be clear you would like to have also fold controls within function blocks only with keyword + bracket (if{}, else{}, for{}, ...) or generally for all bracket sets within a function?

**Comment by hukop** [comment]
I think for all brackets would be best. Before I switched to VS code I used notepad++ and I think the folding there is implemented great. 
Anything that has a opening and closing character (like {}, (), [], /* */) or statement (like #if #endif) can be folded.

**Comment by jpramosi** [comment]
Alright, i think the new options like
```
cfold.withinFunction.enable
cfold.withinFunction.minLines
```
would be suitable for this case.

**Comment by jpramosi** [comment]
Okay i pushed a new version. I hope it's okay that it only folds brackets ({}) within functions (everything else behaves like before).
The reason for only providing brackets is it may require an extra logic and possibly more precise folding ranges on vs-code side with columns.

**Comment by hukop** [comment]
Thanks. Works great now. Obviously more folds like #if #endif inside of functions would be better. But this is already a big help compared to the standard vscode folding.
